name: Build & Deploy to GitHub Pages

permissions:
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  build_and_export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build    # this will do your static export via output: 'export'

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build_and_export
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
